In [7]:
import numpy as np

arr1 = np.array([1,5,8])
arr2 = np.array([[2,3,5],[4,5,6]]) #2x3 array
arr3 = np.array([[2,3,8],[5,7,3]])
arr4 = np.array([[1,2],[5,8]])

print(np.add(arr2,arr2))
print(np.subtract(arr2,arr3))
print("multiplication of arr2 and arr3 :")
print(np.multiply(arr2,arr3))
print(np.divide(arr2,arr3))
print("transpose of matrix is :",arr2.T)
print(np.linalg.inv(arr4))

[[ 4  6 10]
 [ 8 10 12]]
[[ 0  0 -3]
 [-1 -2  3]]
multiplication of arr2 and arr3 :
[[ 4  9 40]
 [20 35 18]]
[[1.         1.         0.625     ]
 [0.8        0.71428571 2.        ]]
transpose of matrix is : [[2 4]
 [3 5]
 [5 6]]
[[-4.   1. ]
 [ 2.5 -0.5]]
