In [55]:
import numpy as np
list = [1,2,3,'a','b']
list2 = [2,6,'a','b']
arr1 = np.array([1,5,8])
arr2 = np.array([2,3,5]) 



print("type of list is: ",type(list))
print("size of list: ",len(list))  # size of list
list[0] = list[1]+list[2]
print("updated list: ",list)
print("slicing ",list[:2])
print("slicing ",list[2:])
list.extend(list2)
print("extended list: ",list)
list.reverse()
print("reversed list: ",list)




print("type of arr1 is: ",type(arr1)) #type of arr
print("size of arr1 is: ",len(arr1)) #size of array
print(arr1.shape) #shape of arr1

print("type of arr2: ",type(arr2))
print(arr2.shape)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)



type of list is:  <class 'list'>
size of list:  5
updated list:  [5, 2, 3, 'a', 'b']
slicing  [5, 2]
slicing  [3, 'a', 'b']
extended list:  [5, 2, 3, 'a', 'b', 2, 6, 'a', 'b']
reversed list:  ['b', 'a', 6, 2, 'b', 'a', 3, 2, 5]
type of arr1 is:  <class 'numpy.ndarray'>
size of arr1 is:  3
(3,)
type of arr2:  <class 'numpy.ndarray'>
(3,)
[ 3  8 13]
[-1  2  3]
[ 2 15 40]
